### ISSUE TITLE
Why do we reverse the digits?

### ISSUE THREAD

**Issue by HazekiahWon** [da03/implicit_chain_of_thought#1]
In the multi-digit multiplication task, why do we reverse the digits in the data?

**Comment by isaaknh** [comment]
probably just improves performance. seeing lower significance digits first probably helps since logically multiplication begins with the ones place, then tens place, etc.

**Comment by da03** [comment]
Yeah that's my intuition, although I didn't really test this. See this paper from Microsoft which has extensive studies on formatting: https://arxiv.org/abs/2311.14737
