### ISSUE TITLE
missing a charachter line 251, implicit_chain_of_thought/src/models/modeling_gpt2_implicit.py

### ISSUE THREAD

**Issue by isaaknh** [da03/implicit_chain_of_thought#2]
don't want to submit a PR for a single character, but on line 251 of implicit_chain_of_thought/src/models/modeling_gpt2_implicit.py there is a missing "e" in the positions_to_substitut: hidden_states[batch_id, **positions_to_substitut**[batch_id]] = states_to_substitute[i][batch_id]

**Comment by da03** [comment]
Oh wow thanks for noticing this!
