### ISSUE TITLE
About the explicit cot baseline

### ISSUE THREAD

**Issue by jiacheng-ye** [da03/implicit_chain_of_thought#9]
Hi Yuntian, thanks for the great work!

I noticed the GPT-2 Small have a 0.41 acc on GSM8K, while after reimplementing I only got around 0.2 acc. Could you provide the training script and some related training tricks for this? e.g., do we need per-digit tokenization, training epoch, lr, etc. 

Thanks for your help.

**Comment by da03** [comment]
Hmm 20% is way too low... Did you train for 15 epochs? The hyperparameters are listed in Appendix E of https://arxiv.org/pdf/2311.01460.pdf. The only difference between GSM8K and the multiplication tasks is that it needs more epochs:

```
export FOLDER=data/gsm8k
export MODEL=gpt2
export EPOCHS=15 # <<<<<<<<<<<<<<<<<<<<<< 15 instead of 1
export LR=5e-5
export BSZ=32
export SAVE=train_models/gsm8k/gpt2/teacher
echo $SAVE
mkdir -p $SAVE
TOKENIZERS_PARALLELISM=false CUDA_VISIBLE_DEVICES=0 stdbuf -oL -eL python src/train_teacher.py \
    --train_path ${FOLDER}/train.txt \
    --val_path ${FOLDER}/valid.txt \
    --epochs $EPOCHS \
    --lr $LR \
    --batch_size $BSZ \
    --base_model $MODEL \
    --save_model $SAVE \
    > ${SAVE}/log.train 2>&1&
```
